### ISSUE TITLE
ATS

### ISSUE THREAD

**Issue by AndrewTal** [sara-nl/attention-sampling-pytorch#7]
Hi,
If the steps of forward propagation remain unchanged. 
The back-propagation part does not use the method in the paper, but uses the default GD based on forward propagation.
Will the effect be worse?

**Comment by jorism1993** [comment]
Hi,

I am not sure what you mean and what your question is. Could you elaborate?

**Comment by AndrewTal** [comment]
Thanks for your quick reply!

For example, the ExpectWithReplacement function is:

```
class ExpectWithReplacement(torch.autograd.Function):
    """ Custom pytorch layer for calculating the expectation of the sampled patches
        with replacement.
    """
    @staticmethod
    def forward(ctx, weights, attention, features):

        axes = [-1] * (len(features.shape) - 2)
        wf = expand_many(weights, axes)

        F = torch.sum(wf * features, dim=1)

        ctx.save_for_backward(weights, attention, features, F)
        return F

    @staticmethod
    def backward(ctx, grad_output):
        weights, attention, features, F = ctx.saved_tensors
        axes = [-1] * (len(features.shape) - 2)
        wf = expand_many(weights, axes)

        grad = torch.unsqueeze(grad_output, 1)

        # Gradient wrt to the attention
        ga = grad * features
        ga = torch.sum(ga, axis=list(range(2, len(ga.shape))))
        ga = ga * weights / attention

        # Gradient wrt to the features
        gf = wf * grad

        return None, ga, gf_
```

if we change this code to:

```
class ExpectWithReplacement(nn.Module):
    def __init__(self):
         super(ExpectWithReplacement, self).__init__()

    def forward(weights, attention, features):
        axes = [-1] * (len(features.shape) - 2)
        wf = expand_many(weights, axes)

        F = torch.sum(wf * features, dim=1)
        return F
```

The model should also be able to be trained end-to-end. 
In this case, will the result be worse than the method in the paper?

Actually, I did not understand the back-propagation method in the paper clearly now, so I have this question before I understand it.

Thanks again!

**Comment by jorism1993** [comment]
> In this case, will the result be worse than the method in the paper?

Not sure, but feel free to investigate this. 

> Thanks again!

You are welcome :-)
